type: "object"

required:
  - inputs
  - output

additionalProperties: false

properties:
  inputs:
    type: array
    items:
      type: string
  output:
    type: string
  const:
    type: array
  aggrs:
    type: array
  attrs:
    type: array
  bools:
    type: array
  loc:
    type: integer
  comment:
    type: string