type: "object"

required:
  - output

additionalProperties: false

oneOf:
  - required:
      - inputs
  - required:
      - host
      - database
      - user
      - tables

properties:
  db:
    type: string
  raw_question:
    type: string
  question_index:
    type: integer
  inputs:
    type: array
    items:
      type: string
  tables:
    type: array
    items:
      type: string
  output:
    type: string
  constants:
    type: array
  functions:
    type: array
  columns:
    type: array
  bools:
    type: array
  filters:
    type: array
  dateorder:
    type: string
  beam_join_columns:
    type: array
    items:
      type: array
      items:
        type: string
  beam_tables:
    type: array
    items:
      type: array
      items:
        type: string
  beam_constants:
    type: array
    items:
      type: array
      items:
        type: [string, number]
  beam_functions:
    type: array
    items:
      type: array
      items:
        type: string
  beam_columns:
    type: array
    items:
      type: array
      items:
        type: string
  beam_filters:
    type: array
    items:
      type: array
      items:
        type: string
  beam_inferred_code:
    type: array
    items:
      type: string
  beam_score_history:
    type: array
    items:
      type: array
      items:
        type: number
  beam_actions:
    type: array
    items:
      type: array
      items:
        type: string
  comment:
    type: string
  sql:
    type: string
  solution:
    type: array
    items:
      type: string
  loc:
    type: integer
  foreign-keys:
    type: array
    items:
      type: array
      items:
        type: string