type: "object"

required:
  - inputs
  - output

additionalProperties: false

properties:
  inputs:
    type: array
    items:
      type: string
  output:
    type: string
  constants:
    type: array
  functions:
    type: array
  columns:
    type: array
  bools:
    type: array
  filters:
    type: array
  dateorder:
    type: string
  comment:
    type: string
  solution:
    type: array
    items:
      type: string
  loc:
    type: integer